### ISSUE TITLE
Help with explanation of some AnetApiSchema types

### ISSUE THREAD

**Issue by sgwatgit** [AuthorizeNet/sdk-dotnet#135]
I looked in the Api documentation but I couldn't find details on these types and was hoping someone could shed light on them.

1. Does the `customerAddressExType` represent an address that exists in the authNet data store, with Ex short for Existing? and `customerAddressType1 is a new address?

2. The `validateCustomerPaymentProfileResponse` has a `string directResponse` property. What does this value represent?

3. Is it because of the auto-generation of the schema that the types do not have any comments or documentation on their properties explaining their purpose? Intellisense feels pretty limited with this library.

Thanks!

**Comment by sgwatgit** [comment]
Can anyone help me out? A little guidance?

**Comment by brianmc** [comment]
Hi @sgwatgit,

Apologies for delay in responding.

1. customerAddressExType is extended from customerAddressType, which in turn is extended from nameAndAddressType. Ex is not indicating "existing", rather "extended" as it has properties in addition to base type. Let us know if that answers your question or you are looking for something more specific based on your use-case.

You can navigate thru all the relationships either in the schema definition (https://apitest.authorize.net/xml/v1/schema/AnetApiSchema.xsd ) or the generated objects https://github.com/AuthorizeNet/sdk-dotnet/blob/master/Authorize.NET/Api/Contracts/V1/AnetApiSchema.generated.cs 

2. validateCustomerPaymentProfileResponse: The directResponse string represents the response from our legacy transaction API, it's the result of the test transaction used to validate the card.  We are absolutely planning to update this method so that the pertinent result information is present in the XML, rather than having to parse this string, which is pretty horrible. You can get more details on the string here:  http://www.authorize.net/content/dam/authorize/documents/AIM_guide.pdf  We will update the API reference with this info, thank-you for the feedback.

3. Yes, the auto-generation of the objects limits the documentation, however, you can find the complete documentation on our developer portal: http://developer.authorize.net/api/reference , along with live request/responses (including try-it) and sample-codes. There has been a suggestion made https://github.com/AuthorizeNet/sdk-dotnet/pull/140 , and we are looking into it.

Hope this helps, thank-you for the feedback and apologies again for the delay in responding.
