### ISSUE TITLE
ANetApiResponse does not return transactionResponse

### ISSUE THREAD

**Issue by seanv1** [AuthorizeNet/sdk-dotnet#182]
using .GetApiResponse returns a ANetApiResponse object but the returned object is missing the transactionResponse and all properties below that (specifically looking for authcode).

Perhaps I am missing something however.

**Comment by markwsanders** [comment]
In my experience, if the GetApiResponse() returns null it is because there was an error. Try checking to see if the response is null and if it is then call GetErrorResponse() to figure out why.

**Comment by Purushottamlpa** [comment]
Hi Seanv1,

Are you still facing this issue? 

If you are, please share the sample code where you faced this issue.

**Comment by Purushottamlpa** [comment]
Thanks for the concern. Since, we didn't hear any update from you, we are closing this issue. If you need further assistance please raise a new issue.

**Comment by shambampow** [comment]
Just want to say that I just had this issue and it was due to the API credentials not being configured on the site I was attempting to use. I have them configured in a web.config and went from a local to the development environment and forgot to bring over the configuration containing the API credentials. It may be worth checking that your credentials exist, as otherwise, you will receive an ANetApiResponse with an empty response.
