### ISSUE TITLE
CustomerGateway.Capture uses approvalCode and not authorizationCode

### ISSUE THREAD

**Issue by StephenPAdams** [AuthorizeNet/sdk-dotnet#192]
Hey gang,

There's an inconsistency going on with the CustomerGateway's Capture method. There's a parameter called approvalCode. I've been using this in practice to use a previously obtained authorizationCode, but the terminology seems off. Is it safe to assume that approvalCode is authorizationCode?

Finally, I've  been looking at the documentation for Customer Information Manager further...in particular the Capture method. I don't see any reference to approvalCode. But here's the trickier thing, there are 2 methods:

Capture a Previously Authorized Amount (see: http://developer.authorize.net/api/reference/#payment-transactions-capture-a-previously-authorized-amount)
Which requires a refTransId (transactionId)

And then there's:

Capture Funds Authorized Through Another Channel (see: http://developer.authorize.net/api/reference/#payment-transactions-capture-funds-authorized-through-another-channel)
Which requires an authCode.

...which one is being used by the CustomerGateway.Capture method in the SDK?

**Comment by adavidw** [comment]
To answer your last question in a strict fashion, CustomerGateway.Capture uses neither method.

CustomerGateway is an implementation of our CIM API, which is an XML API for creating, managing, and charging stored payment information in the form of "profiles". Since the creation of that API, we've created a more all encompassing XML API (catchily named "the Authorize.Net API") that does everything. Profiles. Subscriptions. Transactions with cards. Transactions with tokens. Reporting. Basically everything we do.

There's a ton of overlap between what we documented as the "CIM" API, and the current API. They both have the same endpoint, and all of the calls relating to profile creation and management are the same. The difference is that instead of having CIM-specific transaction calls, we now have a more general _createTransaction_ method, and anything involving charging a profile can be done through that request.

The old CIM transaction methods (_createCustomerProfileTransactionRequest_) still exist, and still work, but you can consider that call deprecated. New work should be done with the _createTransaction_ method.

CustomerGateway is still in the SDK for backward compatibility. If you're already using CustomerGateway and want to keep using it, that's fine. In that case, all you'd need to know is that "approvalCode" is indeed equivalent to "authorizationCode". But, _you'd only ever need the auth code when you are capturing a transaction that was authorized from a different source than Authorize.Net_ (like a voice auth or authorizing through another gateway account or terminal). When you capture a transaction that you previously authorized _somewhere else,_ CustomerGateway is making a call to _createCustomerProfileTransactionRequest_ with the "transaction" parameter set to "profileTransCaptureOnly". Then, the auth code is sent as "approvalCode".

If you're just trying to capture a transaction where the authorization was already done on Authorize.Net, the key piece of information is the "transactionId" of the authorization request. In CustomerGateway, that would be done with _createCustomerProfileTransactionRequest_ with the "transaction" parameter set to "profileTransPriorAuthCapture". 

The two examples you linked to in our current API Reference Guide are both using the _createTransaction_ method. Any profile transaction using _createTransaction_ looks just like a non-profile transaction. The only difference is the presence of a <profile> element to designate the profile to charge instead of a <payment> element containing the card info to charge (as seen in [this example](http://developer.authorize.net/api/reference/#payment-transactions-charge-a-customer-profile)).

The difference between the two specific examples you linked to is that the [Capture a Previously Authorized Amount](http://developer.authorize.net/api/reference/#payment-transactions-capture-a-previously-authorized-amount) shows capturing of a transaction that was authorized through us, and [Capture Funds Authorized Through Another Channel](http://developer.authorize.net/api/reference/#payment-transactions-capture-funds-authorized-through-another-channel) shows capturing of a transaction authorized elsewhere.

So, if you were starting from scratch with this SDK, I'd recommend looking at the [sample code](https://github.com/AuthorizeNet/sample-code-csharp/tree/master/CustomerProfiles), and implementing something from there.

**Comment by StephenPAdams** [comment]
@adavidw thank you so much for this descriptive write-up. Very informative and also thorough. 

Unfortunately I'm not starting from scratch, but while I have you here and since you appear to be a wealth of knowledge...I'm currently using the following workflow (which appears to be working, however):

1. If the customer has a customerProfileId in our system with a billingProfileId, authorize the transaction using CustomerGateway.Authorize, otherwise use the raw credit card info and Gateway.Send with an AuthorizeRequest.
2. When the order is ready to be captured, we call CustomerGateway.Capture regardless of the situation in step 1 as we'll have an authorizationCode in both situations.

I know you mentioned we'd only need the approvalCode if capturing a transaction from somewhere other than Authorize.Net, but is there anything wrong with the above workflow...especially if it's working?

**Comment by adavidw** [comment]
The way you describe will work, but the likely side effect will be that the authorization request and the capture request will not be linked in our system. So, you'll have two separate transaction entries, one for the the authorization request and one for the capture request. For reporting purposes, that's likely to get messy or confusing.

If you want to stick with CustomerGateway, I'd still strongly encourage you to use CustomerGateway.PriorAuthCapture with the transaction ID rather than CustomerGateway.Capture with the authorizationCode (or approvalCode).

Besides reporting, there's other good reasons not to do it the way you're doing. Within the card networks, there's no real time verification of the auth code at clearing time. If your system screws up and sends bogus auth codes, we have no way of knowing whether they're good or not. We're just taking you at your word that that's the auth code you got when you authorized it somewhere else. If you send a bogus code, we'll happily send it on for clearing and settlement, and you'll likely end up with chargebacks and/or fines.

Same thing if you use a valid auth code but accidentally send it twice. There is literally no way for us to know that you didn't authorize the card two different times and get the same auth code each time. That seems far fetched, but a more likely valid scenario is that you're doing two different partial capture requests of the same authorization (with the same auth code, of course). We have no way to tell the difference between that valid scenario and you accidentally submitting a capture request twice. So, we'll happily send both requests for clearing, and you'll get a chargeback.

One other good reason not to do it the way you're doing it: The ability to auth a transaction on our system and then later request to capture that transaction by specifying its ID will never go away. I can't say the same about the unlinked capture from an external authorization. Since there is no way for us or anyone but the actual issuing bank to know that the auth code is valid, it's a potential fraud vector. I'm certainly not announcing anything one way or the other, but if the day comes that we have to pull that feature, it'd be nice if developers who didn't actually need to use it weren't using it.

**Comment by StephenPAdams** [comment]
@adavidw thank you so much! You actually inadvertently answered a developer question I submitted to the Auth.Net team about sticking transactions in the pending authorization area even though they've been captured and showing in the settled area of the Auth.Net portal. This sounds like the reason why it's happening, yea?

**Comment by StephenPAdams** [comment]
Also, just an FYI, I don't see the PriorAuthCapture on ICustomerGateway, but it is there in the implementation on CustomerGateway. There may be other missing methods on the interface.

**Comment by adavidw** [comment]
> @adavidw thank you so much!

No problem! I do really enjoy helping and disseminating knowledge, so I'm glad to have helped a little bit.

> This sounds like the reason why it's happening, yea?

100% yes.

With that capture only method, we make no attempt to match the capture request with a previous authorization because a) we already have another method for doing that, and b) it would nearly impossible to do 100% consistently correct.

We could spend a ton of effort building in checks that say "when a capture only request comes in, check the merchant's open authorizations with x days for one with the same auth code, then compare other data to be really sure that this is the transaction they mean. We can't just go by auth code since those aren't unique. Then, once we think we identified the right authorization on our side, mark it as captured and link the two pieces." We _could_ do that, but even then there would be weird edge cases that either wouldn't match or would be a false positive. So, while we _could_ do that, there's no reason why we would since we already have a way to positively identify a previous authorization that we performed for you and say "This. This is the authorization that I did on your system that I want to capture. Please mark it as captured on your end and cause my money to be delivered to me."

**Comment by adavidw** [comment]
> Also, just an FYI, I don't see the PriorAuthCapture on ICustomerGateway, but it is there in the implementation on CustomerGateway.

Huh.

Well I see how you might inadvertently get confused as to which method to choose when we don't even include the right method. Again, we don't pay any attention to this part of the code these days since we prefer everyone to use the main API, but that's still no excuse for not having it in good working order before ignoring it.

I went through ICustomerGateway.cs in my fork and added all the missing methods that I could see so that it matches CustomerGateway.cs. However, I'm not much of a .NET guy, and my Visual Studio installation is borked at the moment, so I can't really test. Everything builds properly in Travis, but Travis fails for an unrelated error in the sample code I haven't had a chance to look at yet.

Would you do me a favor and give me a sanity check by looking at my changes and make sure I didn't leave anything out or mess anything up?
https://github.com/adavidw/sdk-dotnet/commit/4386c2b9576b18180db4ad95ed88223d698f0141

I'll try to get someone to pull it into the main repo soon.

**Comment by StephenPAdams** [comment]
@adavidw looks good to me. And once again, thank you! This was incredibly helpful and actually helped clear up our sticking transaction issue as well.
