### ISSUE TITLE
Orders with line items and discounts don't total appropriately

### ISSUE THREAD

**Issue by StephenPAdams** [AuthorizeNet/sdk-dotnet#206]
Hey gang,

I have a particular situation that doesn't appear to work appropriately. Essentially this is situations on our site where a customer's total is being authorized too much. Consider the following scenario:

- Customer adds an item to their cart that is $99.00
- Customer lives in a taxable area (5%)
- Customer's shipping rate is $9.00
- Customer adds a 15% off promo code
- Total ends up being $98.10 (formula as follows: $99.00 - ($99.00 * 0.15) + ($99.00 *0.05) + $9.00)

The problem occurs when I use the AuthorizeNet.Order object with AddLineItem. When that's done, my Subtotal ends up being the total of the items (in this case $99.00). Then there's the shipping rate ($9.00) and then there's the tax rate ($4.95). If you look in the source code for the Total...it uses Subtotal + ShippingAmount + SalesTaxAmount.

So what effectively happens is the customer's card gets authorized $114.95 instead of $98.10. 

From what I can tell it's because when I set the Amount to be the cost of the items minus the discount...the Authorize.Net SDK will no longer use that value when computing the total if there are any line items.

To me there needs to be a DiscountAmount on the Order level which will be subtracted from the Total if populated. Otherwise the only temporary fix is to not use the AddLineItem at all. 

Thoughts?

**Comment by adavidw** [comment]
Hi @StephenPAdams,

Can you be more specific about which part of the SDK you're using? I ask because the only part of the SDK I see that attempts to create any sort of total is the part for interacting with the old CIM API.

The old standalone CIM API is deprecated in favor of the more holistic "Authorize.Net API", which encompasses the Customer Profiles features (previous available as "CIM"), the Recurring Billing features (previously "ARB), the Fraud Transaction Management features and so on.

When using the "Authorize.Net API", the "amount" field you pass to the SDK doesn't have any relation to the line items or tax items or shipping or any other items you add. It's up to you to make sure that the amounts you send for those other fields make sense for the "amount" value that you're sending. Whatever you send for "amount" is the amount that's charged, regardless of any other line item values you're sending.

If you haven't already, take a look at our [sample code for the Authorize.Net API](https://github.com/AuthorizeNet/sample-code-csharp), and see if calling things that way could help you.

**Comment by StephenPAdams** [comment]
Yeah, I do believe you're right re: interacting with the old CIM API. I was explicitly talking about the Order object. Example here: 
https://github.com/AuthorizeNet/sdk-dotnet/blob/master/Authorize.NET/CIM/Order.cs

If you see line 52 for Subtotal and line 61 for Total.
