### ISSUE TITLE
CIM Transaction Response is parsed incorrectly upon transaction error

### ISSUE THREAD

**Issue by TrevorW** [AuthorizeNet/sdk-dotnet#57]
Reported in detail in the developer community here: https://community.developer.authorize.net/t5/Integration-and-Testing/CIM-AuthorizeAndCapture-Invalid-Response-on-Sandbox/td-p/49201/highlight/false

**Comment by brianmc** [comment]
We recently added the ability to use charge profiles using the standard CreateTransaction method rather than CreateCustomerProfileTransaction.  This does not involve any parsing of the direct response and we will be updating the SDK methods to use that route.  Our new controller model can also be used to call this API and I have added a new sample to demonstrate that SDK usage (https://github.com/AuthorizeNet/sdk-dotnet/blob/master/AuthorizeNETtest/Api/Controllers/SampleTest/CreateTransactionSampleTest.cs) and you can also see the API example here http://developer.authorize.net/api/reference/#payment-transactions-charge-a-customer-profile
