### ISSUE TITLE
Bug: CIM Authorize/Capture returns approved false every call

### ISSUE THREAD

**Issue by tig4647** [AuthorizeNet/sdk-dotnet#61]
I have tried multiple times and each time I do an authorize/Capture using a customer profile and Authorize.order object, the response comes back as approved=false although in the sandbox I show a transaction approval. When I charge the card through AIM, it works fine.
This seems specific to CIM

**Comment by RobARichardson** [comment]
I'm seeing the same behavior as well.

**Comment by brianmc** [comment]
Thanks guys, while we're looking into this there is an alternative now to using createCustomerProfileTransactionRequest. We've recently updated our standard createTransaction method to accept profiles and we would actually like to deprecate createCustomerProfileTransaction so that developers have one method for doing payments regardless of the payment data (e.g. cards, payment profiles, bank accounts, apple pay, etc).

Snippet below, here's the full code sample:  https://github.com/AuthorizeNet/sdk-dotnet/blob/master/AuthorizeNETtest/Api/Controllers/SampleTest/CreateTransactionSampleTest.cs

````csharp
            //create a transaction
            customerProfilePaymentType profileToCharge = new customerProfilePaymentType();
            profileToCharge.customerProfileId = customerProfileId;
            profileToCharge.paymentProfile = new paymentProfile { paymentProfileId = paymentProfileId};

            var transactionRequestType = new transactionRequestType
            {
                transactionType = transactionTypeEnum.authCaptureTransaction.ToString(),
                //amount = SetValidTransactionAmount(Counter),
                amount = 10,
                profile = profileToCharge
            };
            var createRequest = new createTransactionRequest
            {
                refId = RefId,
                transactionRequest = transactionRequestType,
            };
            //create 
            var createController = new createTransactionController(createRequest);
            createController.Execute();
            var createResponse = createController.GetApiResponse();
````

Apologies if this is actually what you are referring to, we use AIM to refer to a couple of different APIs so that confusion lies on us.

Cheers,

Brian

**Comment by tig4647** [comment]
This was in regards to the existing Methods. I have tried the new method and in the sandbox everything works fine but in production, I am not receiving a transactionID or anything else in production. the values are simply nothing. I am using the code as you suggest. I updated my system to the new API and went live based on my sandbox testing. This is causing a large issue for me.

**Comment by brianmc** [comment]
We'll do our best to get an update to you by EOD tomorrow Jason.

**Comment by tig4647** [comment]
The new method is working as I stated in another bug report, however the existing call still does not work. I do understand that your team is deprecating this functionality
