### ISSUE TITLE
CIM AuthorizeAndCapture: Successful ResponseCode but Approved is false, with no errors

### ISSUE THREAD

**Issue by bradtpm** [AuthorizeNet/sdk-dotnet#72]
When trying to AuthorizeAndCapture using CIM, I am receiving a successful ResponseCode, but Approved is false. I tried the Unit Test from github and received the same message.

Someone else is also experiencing this posted on the forums: https://community.developer.authorize.net/t5/Integration-and-Testing/CIM-AuthorizeAndCapture-Approved-flag-set-to-false/m-p/49633#M25180

There are no error messages and am at a loss right now as to solve the problem.

**Comment by brianmc** [comment]
Thanks Brad, we're looking into this issue but luckily there is an alternative now to using createCustomerProfileTransactionRequest and we hope it's actually a better alternative. We've recently updated our standard createTransaction method to accept profiles and we would actually like to deprecate createCustomerProfileTransaction so that developers have one method for doing payments regardless of the payment data (e.g. cards, payment profiles, bank accounts, apple pay, etc).

Snippet below, here's the full code sample:  https://github.com/AuthorizeNet/sdk-dotnet/blob/master/AuthorizeNETtest/Api/Controllers/SampleTest/CreateTransactionSampleTest.cs

````csharp
            //create a transaction
            customerProfilePaymentType profileToCharge = new customerProfilePaymentType();
            profileToCharge.customerProfileId = customerProfileId;
            profileToCharge.paymentProfile = new paymentProfile { paymentProfileId = paymentProfileId};

            var transactionRequestType = new transactionRequestType
            {
                transactionType = transactionTypeEnum.authCaptureTransaction.ToString(),
                //amount = SetValidTransactionAmount(Counter),
                amount = 10,
                profile = profileToCharge
            };
            var createRequest = new createTransactionRequest
            {
                refId = RefId,
                transactionRequest = transactionRequestType,
            };
            //create 
            var createController = new createTransactionController(createRequest);
            createController.Execute();
            var createResponse = createController.GetApiResponse();
````

Apologies if this is actually what you are referring to, we use AIM to refer to a couple of different APIs so that confusion lies on us.

Cheers,

Brian

**Comment by bradtpm** [comment]
This new way to submit the transaction worked for me. Thank you
