### ISSUE TITLE
CIM Credit Card AVS Fail does not return meaningful error

### ISSUE THREAD

**Issue by tig4647** [AuthorizeNet/sdk-dotnet#73]
Anytime we have an AVS mismatch (where zip/street is a no match) the system simply returns an e0027 and nothing else. There are no errors in the transactions nor anywhere else.
E0027 is not very specific and does not help. 
This is specific to CIM.

**Comment by Dthurman** [comment]
Can I get more details of your scenario?

Are you creating a transaction using a customer payment profile that has an AVS mismatch?
Are you using Gateway or Controller model?
Anything else I should know to repro the issue?

Thanks

**Comment by tig4647** [comment]
I am using the controller model
I do NOT validate the credit card at the time of profile creation.
So when I attempt a charge, on an AVS mismatch I get a E0027 error.
We would prefer to not do test authorizations as we have to pay for them.
I apologize for not being more thorough  in my description

**Comment by brianmc** [comment]
Hi Jason,
If you use the standard CreateTransaction for charging profiles, rather than the CIM version you have access to the full AVS response.

You should be able to test this with the sample test values here:  http://developer.authorize.net/tools/errorgenerationguide/

E.g. to simulate a bad zip code AVS, update your payment profile billing zip to 46201, then when you do a createTransaction with that profile you should get an AVSResponse of A  (in the AVSResponse field of response)

Here's a sample of the code to charge a profile:
https://github.com/AuthorizeNet/sdk-dotnet/blob/master/AuthorizeNETtest/Api/Controllers/SampleTest/CreateTransactionSampleTest.cs

**Comment by tig4647** [comment]
I am using the code above. In sandbox, everything is fine when I move to production and do a similar test(ensuring no zip/street match) I always get a E0027 response.
My workflow is as such:
I create the customer profile
I create the Payment profile(without verification)
I then use the create transaction controller(as seen below, sorry it is VB)

 Dim profileTocharge As customerProfilePaymentType = New customerProfilePaymentType
        profileTocharge.customerProfileId = customerProfileId
        profileTocharge.paymentProfile = New Api.Contracts.V1.paymentProfile With {.paymentProfileId = cardProfileId}



        Dim transRequestType As New transactionRequestType With {.amount = saleAmount, _
                                                                   .profile = profileTocharge, .transactionType = transactionTypeEnum.authCaptureTransaction.ToString()}

        Dim createRequest = New createTransactionRequest With {.refId = InvoiceNumber, .transactionRequest = transRequestType}

        Dim createController = New createTransactionController(createRequest)



        Dim response As New PaymentServiceResponse
        Try
            createController.Execute()
            Dim authResponse = createController.GetApiResponse

**Comment by tig4647** [comment]
Here is the result in production. Notice that tranasction is nothing and in message is E0027. 
ages.resultCode
Error {1}
?authResponse.messages.message
{Length=1}
    (0): {AuthorizeNet.Api.Contracts.V1.messagesTypeMessage}
?authResponse.messages.message(0).text
Nothing
?authResponse.messages.message(0).code
"E00027"

authResponse.transactionResponse
{AuthorizeNet.Api.Contracts.V1.transactionResponse}
    accountNumber: Nothing
    accountType: Nothing
    authCode: Nothing
    avsResultCode: Nothing
    cavvResultCode: Nothing
    cvvResultCode: Nothing
    errors: Nothing
    messages: Nothing
    prePaidCard: Nothing
    rawResponseCode: Nothing

**Comment by brianmc** [comment]
Hi Jason,

Thanks once more for the details, that really helped us diagnose the issue.  We have identified an issue with this method where the responses are not fully populated when AVS filter is enabled (hence the decline).  I suspect if you enabled AVS in your sandbox account you would see the same thing as production.

We are working on getting a fix out as soon as we can - this is an API issue, not SDK so that always takes a little longer. In the meantime the workaround would be to go back to using CIM Charge methods (old method - https://github.com/AuthorizeNet/sdk-dotnet/blob/master/AuthorizeNETtest/CustomerGatewayTest.cs )  If there are issues with that they should only be on the SDK side and we can provide immediate fixes for those.

I apologize for this issue and appreciate your patience as we validated it and work on a fix. If you get a chance send your email address to developer@authorize.net, I'd love to respond to you directly over email as well.

Brian

**Comment by simtay111** [comment]
I understand you guys are all working on this currently, I just wanted to add my situation in case it helps. I am getting the fully empty responses on the transaction except for the message which is a joined code plus message (IE "E00087BlahBlahBLah)  Anyway, just throwing this out there for another case for you guys if it helps.  Seems to be related!  Thanks for working on everything!  Saves a lot of time not having to write the SDK myself :dancers: 

I am using the SDK 1.8.3 and using it simply like this:

            var custGateway = new CustomerGateway(AuthNetCredentials.ApiLogin, AuthNetCredentials.TransactionKey, ServiceMode.Test);

            var profileId = paymentInfo.CustomerId;
            string paymentProfileId;
            if (string.IsNullOrEmpty(profileId))
            {
                var customer = custGateway.CreateCustomer(paymentInfo.PayerEmail, paymentInfo.PayerName);

                profileId = customer.ProfileID;
                paymentProfileId = custGateway.AddCreditCard(profileId, paymentInfo.CardNumber,
                    int.Parse(paymentInfo.CardExpirationMonth),
                    int.Parse(paymentInfo.CardExpirationYear), paymentInfo.CardCvc, new Address()
                    {
                        Country = paymentInfo.CardAddressCountry,
                        City = paymentInfo.CardAddressCity,
                        State = paymentInfo.CardAddressState,
                        Street = paymentInfo.CardAddressLine1 + " " + paymentInfo.CardAddressLine2,
                        Zip = paymentInfo.CardAddressZip
                    });

            }
            else
            {
                var customer = custGateway.GetCustomer(profileId);
                paymentProfileId = customer.PaymentProfiles[0].ProfileID;
            }


            var captureResponse = custGateway.AuthorizeAndCapture(profileId, paymentProfileId, paymentInfo.Amount);

The captureResponse is an empty object essentially!

**Comment by dcartwright** [comment]
Are there any updates on this issue? Whenever I trigger an error of any kind in the sandbox, I get an E0027 message code and zero details. This is a blocker for me on using this API in production since I wouldn't be able to provide meaningful feedback to users. I would like to know whether we need to budget time to re-write our code base (again!) back to the old API vs. continuing to wait on a fix for the new API.

**Comment by brianmc** [comment]
Hi @dcartwright, we have a fix for this and we're currently trying to find it a slot in an upcoming release.  It's really tough to give dates but our goal is to get this out sometime in the next 3 - 6 weeks.

Brian

**Comment by brianmc** [comment]
Not sure we made it in the 3 - 6 week range but fairly close.  This one is fixed.
