### ISSUE TITLE
Pascal casing should be used when defining classes, structs, & interfaces

### ISSUE THREAD

**Issue by RobARichardson** [AuthorizeNet/sdk-dotnet#90]
There are quite a few class definitions in this SDK that do not use proper Pascal casing.   

Examples:
- createTransactionRequest
- transactionRequestType
- lineItemType
- etc, etc, etc.

These definitions violate the standard C# conventions defined by Microsoft:
https://msdn.microsoft.com/en-us/library/vstudio/ms229040(v=vs.100).aspx

**Comment by brianmc** [comment]
Hi Rob, you're quite right, the reason these classes are not properly Pascal case is because they are automatically generated from our API schema.  See our New Model (https://github.com/AuthorizeNet/sdk-dotnet#new-model) and let us know if you think that trade-off to have an SDK that is more or less always in sync is worth sacrificing some language standards.  

We always appreciate your feedback,

Brian

**Comment by icrf** [comment]
As someone trying to get partial authoriztion and split tender working in the old model (mostly seems possibly, if klunky in AIM, not sure it's possible in CIM), I would say I'm willing to give up language conventions for something more likely to be up to date. I'm about to start rewriting in the new model and see if things fare better.

**Comment by brianmc** [comment]
@icrf @RobARichardson  I'm going to close this one but we really do appreciate the feedback.

Thanks,

Brian
