### ISSUE TITLE
SubscriptionGateway.UpdateSubscription() does not update the start date

### ISSUE THREAD

**Issue by bassem-mf** [AuthorizeNet/sdk-dotnet#95]
SubscriptionGateway.UpdateSubscription() does not update the start date even though I set the SubscriptionRequest.StartsOn property.

**Comment by brianmc** [comment]
Hi @bassem-mf, unfortunately this is the current behavior for subscriptions, you cannot edit the start date.  The expected behavior would be that you cannot edit the start date after the subscription STARTS but right now it's after the subscription is created.
We have an open request to change this behavior so thanks for that additional feedback.

Brian

**Comment by bassem-mf** [comment]
I decided to use the XML API directly instead of the SDK. This seems to be the most flexible, complete solution.

It is  hard to tell my users that they cannot update the start date after the subscription is created. They  can do this from the portal so they expect to be able to do it from my software too.

The SDK should simply return the API error message if someone tries to update the start date after the first payment.
